// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Error": {
    "description": "Unfortunately, an error occurred.\n\nYou can try <retry>reloading</retry> the page you were visiting.\n\n",
    "title": "Something went wrong!"
  },
  "IndexPage": {
    "description": "Full-service medical travel organization to the best clinics in South Korea.",
    "title": "Treatment in South Korea with comfort.",
    "title-how": "How to get treatment",
    "steps": {
      "step1": {
        "title": "Submit Your Application",
        "desc": "Start with an easy step—fill out a short form on our website or contact us via messengers (WhatsApp, KakaoTalk, Telegram). Specify your desired treatment area, preferred timeframe, and if possible, attach medical documents (images, test results, reports)."
      },
      "step2": {
        "title": "Consultation",
        "desc": "After receiving your application, we will contact you to clarify details and offer optimal clinic options. We will select a medical institution that matches your request, specialization, and budget. You will receive a preliminary treatment plan and estimated cost, including translation, accommodation, and support services."
      },
      "step3": {
        "title": "Trip to Korea",
        "desc": "Our coordinators will assist with visa processing (if necessary), flight bookings, airport transfers, and accommodation at a hotel or guesthouse near the clinic. We will guide you on how to prepare for your trip and will be available throughout the process."
      },
      "step4": {
        "title": "Treatment",
        "desc": "You will undergo treatment at a modern clinic using advanced technologies and under the supervision of experienced doctors. We will provide interpreter support, assistance with communication with staff, and support until the completion of the entire course. Upon completion of treatment, you will receive the necessary recommendations and documents for follow-up care with your doctor at home."
      }
    },
    "section": {
      "hospitals": "Korean hospitals"
    }
  },
  "ClinicsPage": {
    "title": "Our Clinics",
    "description": "We cooperate with leading medical institutions, offering a wide range of medical tourism services.",
    "readMore": "Read more",
    "view_all_partners": "View all partners",
    "cta": {
      "title": "Ready to start treatment abroad?",
      "description": "Contact us and we will find the best solution tailored to your needs.",
      "button": "Contact us"
    },
    "clinics": {
      "id-hospital": {
        "name": "ID Hospital",
        "description": "Asia’s No. 1 and Korea’s leading plastic surgery hospital."
      },
      "sejong-hospital": {
        "name": "Incheon Sejong Hospital – International Medical Center",
        "description": "Thorough screening, infection control, isolation zones, positive/negative pressure systems, high safety standards."
      },
      "gil-medical": {
        "name": "Gachon University Gil Medical Center",
        "description": "Top oncology center, neurosurgery, and organ transplantation."
      },
      "view": {
        "name": "View Plastic Surgery",
        "description": "An outstanding team of Korea’s top plastic surgeons."
      },
      "live-dental": {
        "name": "Live Dental Hospital",
        "description": "Implants, orthodontics, aesthetic crowns, whitening, cavity treatment, tooth extraction. Over 3,000 foreign patients annually. English, Chinese, and Russian interpreters available."
      },
      "vance-clinic": {
        "name": "Vance Clinic (Namdong-gu)",
        "description": "Contouring, Botox, fillers, lipolytics, skin boosters, skincare. Known for its scientific approach and results-oriented methods. Popular for non-surgical face, nose, and chin corrections."
      }
    }
  },
  "Directions": {
    "departments": "Treatment Areas",
    "dental": {
      "title": "Dentistry",
      "desc": "Implants, surgery, and whitening."
    },
    "plastic": {
      "title": "Plastic Surgery",
      "desc": "Aesthetic and Reconstructive Procedures."
    },
    "dermatology": {
      "title": "Dermatology",
      "desc": "Diagnosis and treatment of skin, hair, and nail diseases."
    },
    "internal": {
      "title": "Internal Medicine",
      "desc": "Treatment of internal organ diseases, including hypertension and diabetes."
    },
    "ent": {
      "title": "Otolaryngology (ENT)",
      "desc": "Treatment of ear, nose, and throat conditions."
    },
    "obgyn": {
      "title": "Obstetrics & Gynecology",
      "desc": "Women's health, pregnancy care, and childbirth."
    },
    "checkup": {
      "title": "Health Check-up",
      "desc": "Full-body screening and diagnostics."
    },
    "ophthalmology": {
      "title": "Ophthalmology",
      "desc": "Vision correction, cataract, and eye disease treatment."
    },
    "oncology": {
      "title": "Oncology",
      "desc": "Cancer diagnosis and treatment using advanced technologies."
    }
  },
  "LocaleLayout": {
    "title": "Medical Tourism in Korea | NS Medical",
    "description": "Top clinics, check-ups, plastic surgery, and more.",
    "keywords": "korea, medical tourism, plastic surgery, health check-up"
  },
  "LocaleSwitcher": {
    "label": "Change Language",
    "locale": "{locale, select, ru {🇷🇺 Русский} en {🇺🇸 English} ko {🇰🇷 Korean} other {Unknown}}"
  },
  "Manifest": {
    "name": "NS Med Travel"
  },
  "Navigation": {
    "name": "NS Med Travel",
    "home": "Home",
    "blog": "Blog",
    "about": "About Us",
    "contacts": "Contacts",
    "clinics": "Clinics",
    "services": "Services",
    "call": "Call us",
    "close_menu": "Close Menu",
    "open_menu": "Open Menu"
  },
  "NotFoundPage": {
    "description": "Please check your browser's address bar or use the navigation to go to a known page.",
    "title": "Page Not Found"
  },
  "PathnamesPage": {
    "description": "",
    "title": "Paths"
  },
  "ContactForm": {
    "formTitle": "Request a callback",
    "getConsultation": "Get consultation",
    "title": "Contact Us",
    "nameLabel": "NAME",
    "emailLabel": "E-MAIL",
    "messageLabel": "MESSAGE",
    "privacyText": "I agree with the privacy policy.",
    "submitText": "SUBMIT",
    "submittingText": "SENDING...",
    "phoneLabel": "Phone number"
  },
  "ThanksPage": {
    "title": "Thank You!",
    "message": "Your message has been successfully sent. We'll contact you soon."
  },
  "Footer": {
    "companyName": "NS Med Travel",
    "companyDescription": "Organization of medical tourism to the best clinics in South Korea.",
    "departments": {
      "title": "Departments",
      "dentistry": "Dentistry",
      "plasticSurgery": "Plastic Surgery",
      "dermatology": "Dermatology"
    },
    "contacts": {
      "title": "Contacts",
      "phone": "+7 (911) 946-07-07",
      "availability": "24/7",
      "email": "Email us",
      "address": "16-1, Hogye-ro 438beon-gil, Gimhae-si, Gyeongsangnam-do"
    },
    "copyright": "© 2025 NS Med Travel. All rights reserved",
    "privacyPolicy": "Privacy Policy",
    "powerby": "Power by Vlad Kim"
  },
  "ModalForm": {
    "getConsultation": "Get consultation",
    "title": "Request a callback",
    "close": "Close modal"
  },
  "Form": {
    "nameLabel": "Full name",
    "namePlaceholder": "Enter your name",
    "emailLabel": "Email",
    "emailPlaceholder": "your@email.com",
    "submit": "Send request",
    "submitting": "Sending..."
  },
  "Partners": {
    "title": "Our Clinics",
    "subtitle": "We cooperate with leading medical institutions, offering a wide range of medical tourism services.",
    "readMore": "Read more",
    "id_title": "ID Hospital Korea",
    "id_description": "Korea's leading plastic surgery hospital, ID Hospital is the No.1 Plastic surgery in Asia.",
    "view_title": "View Plastic Surgery",
    "view_description": "The View Hospital is proud to house a distinguished plastic surgery team consisting of some of the most accomplished plastic surgeons in Korea.",
    "view_all_partners": "View all partners",
    "incheon_sejong_title": "Incheon Sejong Hospital – International Healthcare Center",
    "incheon_sejong_description": "Thorough screening, infection control, isolation zones, positive/negative pressure system, and high-level security.",
    "gachon_gil_title": "Gachon University Gil Medical Center",
    "gachon_gil_description": "Leading oncology center, neurosurgery, and transplantology.",
    "live_dental_title": "Live Dental Hospital",
    "live_dental_description": "Implants, orthodontics, aesthetic crowns, whitening, caries treatment, extractions. 3,000+ international patients annually. Multilingual interpreters.",
    "vance_clinic_title": "Vance Clinic (Namdong-gu)",
    "vance_clinic_description": "Contouring, botox, fillers, lipolytics, skin boosters, skincare. Known for scientific approach and results-focused protocols. Popular for non-surgical jawline, nose, and chin correction."
  },
  "About": {
    "title": "About Us",
    "whoWeAre": {
      "title": "Who We Are",
      "p1": "NS Med Travel is a department of NS Group that provides full support for medical tourism in South Korea.",
      "p2": "We make treatment in Korea comfortable, safe, and accessible. We work with trusted clinics and support our clients at every step."
    },
    "history": {
      "title": "Our Story",
      "p1": "NS Med Travel was born from the desire to help people who not only want to be treated, but also want care and support.",
      "p2": "We’ve walked this path ourselves — searching for doctors, evaluating clinics, and building relationships. Now we share this experience with you."
    },
    "services": {
      "title": "What We Offer",
      "items": [
        "Selection of clinic and doctor",
        "Translation of documents and online consultations",
        "Visa, tickets, and hotel arrangements",
        "Airport pickup and transfers",
        "Personal assistant and interpreter",
        "Full treatment coordination"
      ],
      "note": "You focus on treatment — we handle everything else."
    },
    "workflow": {
      "title": "How We Work",
      "p1": "Just tell us about your case. We’ll find a clinic, discuss the details with doctors, and send you a plan and cost estimate.",
      "p2": "Your journey — from the first call to final check-up — is guided by personal support."
    },
    "team": {
      "title": "Who We Are",
      "p1": "NS Med Travel is staffed by interpreters, coordinators, and medical consultants with experience in healthcare, logistics, and international support.",
      "p2": "We are available 24/7, understand the importance of trust, and treat you like family."
    },
    "cta": {
      "title": "Ready to Start?",
      "description": "Contact us and we’ll help you find the treatment that’s right for you.",
      "button": "Contact Us"
    }
  }
};
export default messages;